name: 'github-action-scp'
description: 'Copy files from GitHub Actions pipeline to remote using SCP'
author: "Tyler O'Brien"
inputs:
  host:
    description: 'Hostname or IP address of remote to copy to'
    required: true
  port:
    description: 'Port to use for scp operation'
    default: 22
  user:
    description: 'Username of remote user'
    required: true
  key:
    description: 'Private SSH key used to identify remote user'
    required: true
  proxy_host:
    description: 'Hostname or IP address of proxy'
    required: true
  proxy_port:
    description: 'Port to use for proxy ssh connection'
    default: 22
  proxy_user:
    description: 'Username of proxy user'
    default: 'bastion'
  proxy_key:
    description: 'Private SSH key used to identify proxy user'
    required: true
  source:
    description: 'Filepath of source'
    required: true
  destination:
    description: 'Filepath of destination'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'copy'
  color: 'purple'