#!/bin/sh

set -eu

REMOTE_SSH_KEY_FILE=remote.key
REMOTE_DESTINATION=$INPUT_USER@$INPUT_HOST:$INPUT_DESTINATION

PROXY_SSH_KEY_FILE=proxy.key
PROXY_COMMAND="ssh -o StrictHostKeyChecking=no -i $PROXY_SSH_KEY_FILE $INPUT_PROXY_USER@$INPUT_PROXY_HOST -W %h:%p"

echo "$INPUT_KEY" > $REMOTE_SSH_KEY_FILE
echo "$INPUT_PROXY_KEY" > $PROXY_SSH_KEY_FILE

chmod 600 $REMOTE_SSH_KEY_FILE
chmod 600 $PROXY_SSH_KEY_FILE

scp -r -o StrictHostKeyChecking=no -i $REMOTE_SSH_KEY_FILE -o ProxyCommand="$PROXY_COMMAND" "$INPUT_SOURCE" "$REMOTE_DESTINATION"
